# Generated by Django 5.0.2 on 2024-02-24 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_fotografia_publicado'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateField(blank='', default=datetime.datetime(2024, 2, 24, 14, 51, 15, 322654)),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='publicado',
            field=models.BooleanField(default='False'),
        ),
    ]
