# Generated by Django 5.0.2 on 2024-02-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='foto',
            field=models.ImageField(blank='True', null='True', upload_to='foto/%Y/%m/%d/'),
        ),
    ]
