# Generated by Django 5.0.2 on 2024-03-07 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0011_alter_fotografia_categoria_alter_fotografia_legenda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='publicado',
            field=models.BooleanField(default='True'),
        ),
    ]
