# Generated by Django 5.0.2 on 2024-03-08 01:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0012_fotografia_likes_alter_fotografia_publicado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curtida', models.BooleanField(default='True')),
                ('fotografia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotografia', to='galeria.fotografia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_like', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
