# Generated by Django 5.0.2 on 2024-02-24 17:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_fotografia_data_fotografia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotografia',
            name='data_fotografia',
            field=models.DateField(blank='', default=datetime.datetime.now),
        ),
    ]
