# Generated by Django 5.0.2 on 2024-02-25 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0008_alter_fotografia_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='clique',
            field=models.IntegerField(default=0),
        ),
    ]
